### ISSUE TITLE
look for food in offhand for iceroad macro

### ISSUE THREAD

**Issue by Huskydog9988** [okx-code/civmodern#21]
Look for food in offhand for iceroad macro auto eat setting, its very annoying when it doesn't.

**Comment by okx-code** [comment]
This is not possible to fully implement in a way that is compliant with CivMC's rules. You'd have to determine if the item in the main hand is usable (so that you don't place it while trying to eat the item in the offhand), and if it's a block, you'd have to read what the cursor is looking at to do so. This would also be really difficult to implement as Minecraft does not expose an obvious method for "does right clicking this item do anything".
